03-19 23:09:26 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-168]
03-19 23:35:48 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Column "INLOG" not found; SQL statement:
select * from user where           inlog = ? and password = ? [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:159)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:126)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:820)
	at play.api.db.AutoCleanConnection$$anonfun$prepareStatement$1.apply(DB.scala:448)
	at play.api.db.AutoCleanConnection$$anonfun$prepareStatement$1.apply(DB.scala:448)
	at play.api.db.AutoCleanConnection.registering(DB.scala:433)
	at play.api.db.AutoCleanConnection.prepareStatement(DB.scala:448)
	at anorm.SimpleSql.getFilledStatement(Anorm.scala:389)
	at anorm.Sql$class.resultSet(Anorm.scala:449)
	at anorm.SimpleSql.resultSet(Anorm.scala:370)
	at anorm.Sql$class.as(Anorm.scala:453)
	at anorm.SimpleSql.as(Anorm.scala:370)
	at models.User$$anonfun$authenticate$1.apply(User.scala:62)
	at models.User$$anonfun$authenticate$1.apply(User.scala:53)
	at play.api.db.DBApi$class.withConnection(DB.scala:82)
	at play.api.db.BoneCPApi.withConnection(DB.scala:275)
	at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:161)
	at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:161)
	at scala.Option.map(Option.scala:145)
	at play.api.db.DB$.withConnection(DB.scala:161)
	at models.User$.authenticate(User.scala:53)
	at controllers.Application$$anonfun$2.apply(Application.scala:17)
	at controllers.Application$$anonfun$2.apply(Application.scala:16)
	at play.api.data.Mapping$$anonfun$verifying$2.apply(Form.scala:493)
	at play.api.data.Mapping$$anonfun$verifying$2.apply(Form.scala:492)
	at play.api.data.validation.Constraint.apply(Validation.scala:21)
	at play.api.data.Mapping$$anonfun$collectErrors$2.apply(Form.scala:519)
	at play.api.data.Mapping$$anonfun$collectErrors$2.apply(Form.scala:519)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:309)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.data.Mapping$class.collectErrors(Form.scala:519)
	at play.api.data.ObjectMapping2.collectErrors(ObjectMappings.scala:6)
	at play.api.data.Mapping$$anonfun$applyConstraints$1.apply(Form.scala:514)
	at play.api.data.Mapping$$anonfun$applyConstraints$1.apply(Form.scala:513)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at play.api.data.Mapping$class.applyConstraints(Form.scala:513)
	at play.api.data.ObjectMapping2.applyConstraints(ObjectMappings.scala:6)
	at play.api.data.ObjectMapping2.bind(ObjectMappings.scala:16)
	at play.api.data.Form.bind(Form.scala:55)
	at play.api.data.Form.bindFromRequest(Form.scala:87)
	at play.api.data.Form.bindFromRequest(Form.scala:73)
	at controllers.Application$$anonfun$authenticate$1.apply(Application.scala:32)
	at controllers.Application$$anonfun$authenticate$1.apply(Application.scala:31)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:217)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:109)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:109)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:108)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:106)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2.apply(Action.scala:106)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$2.apply(Action.scala:99)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:137)
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1417)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
04-22 10:39:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "A" not found; SQL statement:
INSERT INTO PROTEINCDS VALUES(A, 4.6337, 0.0240, 0.8466)
INSERT INTO PROTEINCDS VALUES(B,4.6122,0.0205,0.8627)
INSERT INTO PROTEINCDS VALUES(C,4.1585,0.0235,0.8338)
INSERT INTO PROTEINCDS VALUES(D,3.0938,0.0197,0.8101)
INSERT INTO PROTEINCDS VALUES(E,2.0315,0.0163,0.8369)
INSERT INTO PROTEINCDS VALUES(F,3.0805,0.0157,0.8878)
INSERT INTO PROTEINCDS VALUES(G,3.5894,0.0171,0.7222)
INSERT INTO PROTEINCDS VALUES(H,2.5034,0.0164,0.8595)
INSERT INTO PROTEINCDS VALUES(I,4.3378,0.0243,0.9330)
INSERT INTO PROTEINCDS VALUES(,1.8689,0.0237,0.7407) [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:722)
04-22 10:39:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "A" not found; SQL statement:
INSERT INTO PROTEINCDS VALUES(A, 4.6337, 0.0240, 0.8466) [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:967)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:722)
04-22 10:40:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO PROTEINCDS VALUES('B',4.6122,0.0205,0.8627)
INSERT[*] INTO PROTEINCDS VALUES('C',4.1585,0.0235,0.8338)
INSERT INTO PROTEINCDS VALUES('D',3.0938,0.0197,0.8101)
INSERT INTO PROTEINCDS VALUES('E',2.0315,0.0163,0.8369)
INSERT INTO PROTEINCDS VALUES('F',3.0805,0.0157,0.8878)
INSERT INTO PROTEINCDS VALUES('G',3.5894,0.0171,0.7222)
INSERT INTO PROTEINCDS VALUES('H',2.5034,0.0164,0.8595)
INSERT INTO PROTEINCDS VALUES('I',4.3378,0.0243,0.9330)
INSERT INTO PROTEINCDS VALUES('J',1.8689,0.0237,0.7407)"; SQL statement:
INSERT INTO PROTEINCDS VALUES('B',4.6122,0.0205,0.8627)
INSERT INTO PROTEINCDS VALUES('C',4.1585,0.0235,0.8338)
INSERT INTO PROTEINCDS VALUES('D',3.0938,0.0197,0.8101)
INSERT INTO PROTEINCDS VALUES('E',2.0315,0.0163,0.8369)
INSERT INTO PROTEINCDS VALUES('F',3.0805,0.0157,0.8878)
INSERT INTO PROTEINCDS VALUES('G',3.5894,0.0171,0.7222)
INSERT INTO PROTEINCDS VALUES('H',2.5034,0.0164,0.8595)
INSERT INTO PROTEINCDS VALUES('I',4.3378,0.0243,0.9330)
INSERT INTO PROTEINCDS VALUES('J',1.8689,0.0237,0.7407) [42000-168]
